redirects:
  quick-start: get-started/quick-start.md
  how-to/github-action: ci/introduction.md
  project-structure/config.yml: reference/project-structure/config.md 
  how-to/compare-reports: /reference/piperider-cli.md
  piperider-cli: /reference/piperider-cli.md
  data-quality-assertions/assertion-configuration: get-started/run/assertions.md
  data-quality-assertions/custom-assertions: get-started/run/assertions.md
  
